/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import javax.swing.JFrame;

/**
 * Class where the main JFrame's components are called and defined
 * @author Shirley Pinto
 */
public class JFrameJC extends JFrame {
    
    /**
     * Creates new form UI
     */
    public JFrameJC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     private void initComponents() {

        jPanelButtons = new ActionButtons();
        jPanelBody = new BodyPanel();
        jMenuBar = new MenuBar();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jPanelBody.formWindowOpened(evt);
            }
        });
        
        getContentPane().add(jPanelButtons, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(jPanelBody, java.awt.BorderLayout.CENTER);

        setJMenuBar(jMenuBar);

        pack();
    }
    
    /**
     * Main method to invoke the JFrame 
     * @param args the command line arguments 
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameJC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameJC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameJC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameJC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameJC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private MenuBar jMenuBar;
    private BodyPanel jPanelBody;
    private ActionButtons jPanelButtons;
    // End of variables declaration                   
}